spring.application.name=GatewayService
server.port=8000

eureka.client.service-url.defaultZone=http://localhost:9000/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AuthService1
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=wallet-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://WalletService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/wallet/**

spring.cloud.gateway.server.webmvc.routes[2].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://TransactionService
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/transactions/**